"""Adapters implement these interfaces; ingestion never imports an adapter."""

from contextlib import AbstractContextManager
from typing import Protocol

from .models import CatalogueSnapshot, ListingEntry, ListingPage, Offering, SyncReport


class CatalogueSource(Protocol):
    def listing(self, number: int) -> ListingPage: ...
    def detail(self, entry: ListingEntry, *, previous: Offering | None = None) -> str: ...


class CatalogueRepository(Protocol):
    def lock(self) -> AbstractContextManager[None]: ...
    def current(self) -> CatalogueSnapshot | None: ...
    def stage(self, snapshot: CatalogueSnapshot, report: SyncReport) -> None: ...
    def publish(self, snapshot: CatalogueSnapshot, report: SyncReport) -> None: ...


class CatalogueReader(Protocol):
    def search(
        self, query: str = "", *, term: str | None = None, limit: int = 50, offset: int = 0
    ) -> tuple[Offering, ...]: ...
    def get(self, source_id: str) -> Offering | None: ...
