/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/status/catalogue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status */
    get: operations["catalogueStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalogue/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Courses */
    get: operations["catalogueCourses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalogue/courses/{course_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Course */
    get: operations["catalogueCourse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalogue/terms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Terms */
    get: operations["catalogueTerms"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness only; database readiness is reported independently.
     */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_api_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CatalogueStatus */
    CatalogueStatus: {
      /**
       * Availability
       * @default unavailable
       * @enum {string}
       */
      availability: "available" | "unavailable";
      /** Reason */
      reason?: ("no_published_snapshot" | "database_unavailable") | null;
      /** Snapshot Id */
      snapshot_id?: string | null;
      /** Published At */
      published_at?: string | null;
      /** Age Seconds */
      age_seconds?: number | null;
      /**
       * Stale
       * @default false
       */
      stale: boolean;
      /** Latest Sync Outcome */
      latest_sync_outcome?: string | null;
      /** Latest Sync At */
      latest_sync_at?: string | null;
      /**
       * Development Fixture
       * @default false
       */
      development_fixture: boolean;
    };
    /** CatalogueTerms */
    CatalogueTerms: {
      /** Terms */
      terms: string[];
      /** Faculties */
      faculties: string[];
      /** Languages */
      languages: string[];
      /** Levels */
      levels: string[];
      status: components["schemas"]["CatalogueStatus"];
    };
    /** Course */
    Course: {
      /** Code */
      code: string;
      /** Titles */
      titles: {
        [key: string]: string;
      };
    };
    /** CourseDetail */
    CourseDetail: {
      /** Code */
      code: string;
      /** Titles */
      titles: {
        [key: string]: string;
      };
      /** Offerings */
      offerings: components["schemas"]["PublicOffering"][];
    };
    /** CoursePage */
    CoursePage: {
      /** Items */
      items: components["schemas"]["CourseDetail"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      status: components["schemas"]["CatalogueStatus"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Meeting */
    Meeting: {
      /** Starts At */
      starts_at?: string | null;
      /** Ends At */
      ends_at?: string | null;
      /**
       * Location
       * @default
       */
      location: string;
      /**
       * Unresolved
       * @default false
       */
      unresolved: boolean;
      /**
       * Cancelled
       * @default false
       */
      cancelled: boolean;
      /** Recurrence */
      recurrence?: string | null;
      /**
       * Excluded Dates
       * @default []
       */
      excluded_dates: string[];
      /**
       * Additional Dates
       * @default []
       */
      additional_dates: string[];
      /** Recurrence Id */
      recurrence_id?: string | null;
      /** Source Uid */
      source_uid?: string | null;
      /**
       * Note
       * @default
       */
      note: string;
    };
    /** ProgrammeAssignment */
    ProgrammeAssignment: {
      /** Programme */
      programme: string;
      /** Version */
      version: string;
      /** Paths */
      paths: string[];
    };
    /** PublicOffering */
    PublicOffering: {
      /** Source Id */
      source_id: string;
      course: components["schemas"]["Course"];
      /** Terms */
      terms: string[];
      /** Ects */
      ects: number | null;
      /** Languages */
      languages: string[];
      /**
       * Levels
       * @default []
       */
      levels: string[];
      /** Lecturer */
      lecturer: string;
      /** Faculty Domain */
      faculty_domain: string;
      /** Schedule Summary */
      schedule_summary: string;
      /** Recurrence Summary */
      recurrence_summary: string;
      /** Meetings */
      meetings: components["schemas"]["Meeting"][];
      /** Assessment */
      assessment: string;
      /** Prerequisites */
      prerequisites: string;
      /** Equivalents */
      equivalents: string;
      /** Assignments */
      assignments: components["schemas"]["ProgrammeAssignment"][];
      /** Calendar Url */
      calendar_url: string | null;
      /** Listing Fingerprint */
      listing_fingerprint: string;
      /** Detail Hash */
      detail_hash: string;
      /** Calendar Hash */
      calendar_hash?: string | null;
      /** Detail Checked At */
      detail_checked_at?: string | null;
      /** Source Url */
      source_url: string;
      /**
       * Meeting State
       * @enum {string}
       */
      meeting_state: "resolved" | "unresolved";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  catalogueStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogueStatus"];
        };
      };
    };
  };
  catalogueCourses: {
    parameters: {
      query?: {
        q?: string;
        term?: string | null;
        faculty?: string | null;
        language?: string | null;
        level?: string | null;
        ects_min?: number | null;
        ects_max?: number | null;
        available_day?: number | null;
        available_from?: string | null;
        available_until?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoursePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalogueCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalogueTerms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogueTerms"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_api_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
